name: sealed_annotations
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/FatulM/dart_sealed/tree/master/sealed_annotations
homepage: https://github.com/FatulM/dart_sealed

version: 2.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  meta: any
  equatable: ^2.0.0

dev_dependencies:
  lints: any
  test: any

# THIS IS NOT THE UPSTREAM REPOSITORY AND ONLY ACCESSIBLE THROUGH GIT:
publish_to: 'none'
