name: sealed_generators
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/FatulM/dart_sealed/tree/master/sealed_generators
homepage: https://github.com/FatulM/dart_sealed

version: 2.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  sealed_annotations: '2.0.0'
  sealed_writer: '2.0.0'
  build: any
  source_gen: any
  analyzer: any
  pub_semver: any

dev_dependencies:
  lints: any
  test: any
  build_test: any

# THIS IS NOT THE UPSTREAM REPOSITORY AND ONLY ACCESSIBLE THROUGH GIT:
publish_to: 'none'

# THIS SHOULD BE OVERRIDDEN IN YOUR OWN PROJECTS:
dependency_overrides:
  sealed_annotations:
    path: ../sealed_annotations
  sealed_writer:
    path: ../sealed_writer
